# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 07c924196c7a6463cded92a9e021245791cfe3110bb8b06e7fc7b0bf3455682fc2ad3459437593ad4ab74047ea3a735ebb776a4309b36abf240379d196ed253b

test:
  secret_key_base: 21312507f8865efa94321086d03ba43b5671d5aeaecaa62eafaa1c4eef1653e8ed4e701c2e9875c41d4fadf8e8ad7cd5ab99160ea7edb1dbba8d7bf64b51d6e8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
